---
- name: Update webserver
  hosts: all
  remote_user: ubuntu

  tasks:
  - name: give permission
    ansible.builtin.shell:
    cmd: chown username foldername

  - name: copy files
    src: /etc/apache2/conf
    dest: /var/www/html

  - name: update apache
    ansible.builtin.apt:
    name: httpd
    state: current